title: "Carolina Mattsson"
image: /assets/img/carolina-website.jpg
description: "Researcher at <a href="https://centai.eu">CENTAI</a>"
theme: jekyll-theme-minimal
pagelist:
  -
    title: Research
    url: pages/research.html
  -
    title: Leadership
    url: pages/leadership.html
  -
    title: Teaching
    url: pages/teaching.html
email: "mailto:carolina.mattsson@centai.eu"
paper: /assets/files/Mattsson_JMP.pdf
cv: /assets/files/Mattsson_CV_2023-05-01.pdf
