title: "Carolina Mattsson"
image: /assets/img/carolina-website.jpg
theme: jekyll-theme-minimal
pagelist:
  -
    title: Research
    url: pages/research.html
  -
    title: Leadership
    url: pages/leadership.html
  -
    title: Teaching
    url: pages/teaching.html
email: "mailto:mattsson.c@northeastern.edu"
cv: /assets/files/Mattsson_CV_2026.pdf
